### ISSUE TITLE
Hydrogen Phase/Pre-Helium

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#100]
How long are you expecting the 3H phase to last before the first decay? I've been running it off and on for multiple days and I'm at 9.6e7 3H and haven't had a single decay. I artificially bumped it 10x and it immediately started producing electrons and He, so I know it works.

I'd like to suggest considering maybe setting some base threshold where if you haven't unlocked He, it artificially increases the chance of decay until you do. Or if you intend for prestiges to happen before unlocking He, making that a little more obvious. Or even offering the ability to outright buy a small bundle of He with xH.

**Comment by HeinousTugboat** [comment]
So, actually crunching some numbers, I think it takes 5.60516E8 3H before it'll decay even once with how the formula's currently sorted, unless I'm misunderstanding the use of Math.floor() [here](https://github.com/angarg12/nucleogenesis/blob/3a4b7305fdd92ac6b5de4791d4f5afc0b98b1ef5/src/scripts/component/matter.js#L36). 

```
          let halfLife = decay.half_life;
          let exponent = 1/halfLife;
          let factor = Math.pow(0.5, exponent);
          let totalProduction = Math.floor(number - number * factor);
```

Working backwards from this snippet, `totalProduction` can't be non-zero until you have at least 
 560515947.9 3H.. which is like.. 48 hours if you have 100 Tier X Hydrogen generators..

**Comment by angarg12** [comment]
Thanks for the feedback.

Before we used a Poisson distribution for low decays such that you would get a decay every now and then. However we had a lot of problems so we removed it.

In any case the game needs a complete rebalancing pass. My current idea is to make the exotic matter production curve lower and flatter. That means that you will get less exotic matter but you will get more over time, so idling pays off.

Also a new batch of exotic upgrades is on the works, which should speed up the early game stage.

**Comment by HeinousTugboat** [comment]
That makes sense! Is there anything I can help with?

**Comment by angarg12** [comment]
Giving feedback and maybe some ideas is enough, unless you want to get involved in the development :).

The experience that I want to create is an idle game where you make decisions, leave it working for a while, come back and rethink your strategy. Right now the pacing is not quite there.

The onboarding/early game pace is off. First, not many things happen, and then a lot gets unlocked quickly. Also the dropoff formula for exotic matter and dark matter is too step so it is better to do quick prestiges rather than idling. Lastly, numbers go up so fast that you don't really need to pay attention to the upgrades you buy or the synergies between elements.

I will put in the backlog a bunch of tasks related to balance and some new upgrades to try to tune the pacing. This will require quite a lot of trial and error, so I expect these features to take a while to develop.

**Comment by HeinousTugboat** [comment]
I would actually love to get involved in the development! I've gone ahead and forked the repo and have a local branch running. Let me know if there are any small things you need taken care of, otherwise I'll start poking around at the open issues. 

Also, I'll start putting together a spreadsheet looking at, at the very least, the early game progression. My gut tells me the coefficients are probably a bit off, I know when I was playing Generator 7 was oddly more efficient than 5 or 6, so I wound up with more 7s consistently.

Would you rather I put this into the wiki or into an issue?

**Comment by angarg12** [comment]
That's awesome :+1: 

Feel free to contribute to the Wiki, actually I should come around it some day and fill it with some basic information (all I ever did was isotopes).

I will go through my notes and open some issues with stuff that I want to add or change, that way we can have a place to discuss them.
