### ISSUE TITLE
Only using large bootstrap breakpoints in sidebar.

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#105]
https://github.com/angarg12/nucleogenesis/blob/7ade6eedf5d285b551a39f5c14c64e3cdc400560/src/html/views/sidebar.html#L11

I can fix this, but I'm not sure how you want it to look. The problem is if the large breakpoint is only active on windows larger than 1200px wide. On any screens narrower, it just sort of collapses into itself since. This can be fixed by just changing it to `col-sm-2`, or if you'd prefer it be narrower, `col-sm-1` for instance.

**Comment by angarg12** [comment]
I never really thought about it, but now that I pay attention to it I actually like the condensed way better.

In a wide screen it looks like this

![screenshot 2017-09-07 08 38 14](https://user-images.githubusercontent.com/5389189/30149521-322a2c02-93a8-11e7-8304-0863dc6dbae6.png)

I find it annoying because we are already a bit short of real estate. In a narrow screen it looks like this

![screenshot 2017-09-07 08 38 08](https://user-images.githubusercontent.com/5389189/30149547-4ba75ef2-93a8-11e7-9196-a2b5f8f652ca.png)

I like this second one better because it still has a little bit of margin but wastes less space.

If you could fix that, it would be wonderful. However, I wouldn't spend too much time worrying about the GUI since I want to scrap most of it anyway (but only after balancing).
