### ISSUE TITLE
Purchasing Elements out of order

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#110]
If you skip an element on the periodic table, it doesn't increase the price of any smaller elements. If this is intentional, go ahead and close this out. Maybe think about rewording the verbiage on there. There's a pretty solid possibility that optimal play will involve skipping a huge chunk of the table, though. I have a sneaking suspicion that saving up dark matter and buying Tin very early will probably be a very potent strategy, due to how exotic particles are calculated per isotope but not adjusted until after all of them have been calculated.

**Comment by angarg12** [comment]
Buying heavy elements does indeed increase the price of lighter ones. It may not seem so if they are very cheap because the price will increase slowly, but that is part of the balancing.

I'm also sure the optimal play involves skipping lots of elements, and that is part of the strategy. Maybe Tin is a great early game strategy. Or maybe Krypton because it has a lot of ions, or Carbon/Oxygen because they have lots of compounds. Or the heaviest elements because they have long decay paths and release tons of energy.

Hopefully the game is so complex that it will be hard to determine an optimal strategy, and there is plenty of room for people to explore different possibilities.

**Comment by HeinousTugboat** [comment]
Gonna go ahead and close this out. I checked the prices by buying the heaviest elements and it's definitely increasing the prices across the board. Must just've been a very tiny increase I missed before. My apologies!
