### ISSUE TITLE
Hide achievements before earnable?

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#113]
The achievements tab is.. hefty. What if we hide achievements for elements we haven't unlocked yet? That might cut it down.

**Comment by angarg12** [comment]
Yes, this is a good idea.

**Comment by angarg12** [comment]
Draft:

We already have in place two mechanisms that together could help this.

First, upgrades can define dependencies, and they are visible only if the dependencies are met.

Second, there are unlocks. Unlocks are very similar to achievements but don't show up anywhere in the GUI.

I implemented unlocks because I needed some place to put arbitrary checks to gate progression, and when to show/hide things in the GUI. This is how exotic and dark matter are unlocked right now.

Putting together these two concepts, we could define dependencies for achievements and tie these to unlocks. Unlocks are arbitrary functions so you can put there anything you want.
