### ISSUE TITLE
Isotope Molecules?

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#121]
We have Isotopes, we have molecules.. por que los dos? [Heavy water](https://en.wikipedia.org/wiki/Heavy_water) is a super important substance in nuclear science, and I'm positive there exist other compounds with isotopes in them. Seems like that's something we should consider.

**Comment by angarg12** [comment]
We used to have compounds with isotopes, at least Deuterium and Tritium. Chances are I still have the data file lying around somewhere.

I deleted these reactions because they are essentially redundant and somewhat confusing.

All deuterium reactions have a counterpart with 1H. In the real world heavy water is important, but from the gameplay perspective H2O and D2O are pretty much identical.

Also it would probably be quite confusing for players to have something like H2O and 2H2O, particularly if they aren't chemistry inclined.

I feel like this is one of those cases where being faithful to science doesn't pay off in gameplay.

**Comment by HeinousTugboat** [comment]
Ah! That's a pretty good reason why! Looking into it more, they're actually called [isotopologues](https://en.wikipedia.org/wiki/Isotopologue) and they don't really do anything interesting in chemical reactions. They appear to mostly just be of interest to forensic and geologic investigations.

Thanks!
