### ISSUE TITLE
Exotic Upgrades Synergy 1 and 2 same price as Synergy 3 and 4

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#122]
Not sure if this is intentional:

![image](https://user-images.githubusercontent.com/15902166/30276674-922f465e-96d3-11e7-8c37-456cd0cf825e.png)

**Comment by angarg12** [comment]
I just plugged some placeholder values so don't take them too seriously.

We have a very tough problem to solve with balance. Essentially we need to balance:

Generators price/production/price exponent.
Upgrades prices.
Exotic prestige formula.
Exotic upgrades prices.

And each one of these feeds into the other.

I was thinking a bit about it and probably the best way to deal with it is to simplify, fix some values and run simulations to tune the rest. For example, we could start with fixed generators and all upgrades unlocked (ignore prestige to begin with), and run simulations to check which price ranges are reasonable. Once we fix that we can iterate and run simulations with other values.

I don't think we can hope to fix balance by hand so running simulations seems like the best approach. I would need to brainstorm a bit since I'm not sure about how to approach the problem.

For reference, the current price of generators and upgrades is taken directly from Cookie Clicker.

Since this issue is really part of balancing, we could close it and move the discussion to #103.

**Comment by HeinousTugboat** [comment]
That makes total sense, yeah. I'll go ahead and close this then. Where would you rather I spend my energy, on #13 and UI-related work or on #103 and #104 doing sim/analysis-oriented work?

**Comment by angarg12** [comment]
Right now I would rather work on balance and pacing. Once we get done with that we can pretty much playtest the game, get feedback and so on, while GUI is mostly cosmetic and QoL.
