### ISSUE TITLE
Embed bot into the code via tests?

### ISSUE THREAD

**Issue by angarg12** [angarg12/incremental_table_elements#126]
This is a question for @HeinousTugboat.

Since we are relying on the bot more and more I wanted to make it as seamless as possible.

I came up with the idea to hack tests to embed the bot behaviour into the code. Simply put, inside a test you loop, manually calling the update function and doing the bot logic.

That way we can leverage the actual app code and focus on the logic and statistics reports.

The biggest downside is that with all the overhead is not very efficient. I am able to simulate 1 hour of very simple bot in 1 minute.

Let me know if this is a direction you would like to go to.

**Comment by HeinousTugboat** [comment]
So, I've been thinking about this. Firstly, I don't think integrating my simulation into the test code would be particularly beneficial for two reasons. You can simulate 1 hour per minute, but as my sim currently stands it can process 24 hours in about 20 seconds. The second reason is because an integral part of my sim is that it produces massive (100+ mb) data files dumping basically every piece of information with associated tick number so we can deeply analyze the events.

However, I do think you have a great idea here. For now, I think we should continue using my sim for exploration, to help figure out our basic balance and checkpoints, and then once we've started to formalize those, I think we should absolutely implement a series of checks with the same strategies I've been using as integration tests, so we can ensure that, for instance, after 24 hours of basic play the player has reached a particular milestone, unlock, or is where we want them to be. That way we can ensure we prevent any regressions as we continue to adjust balance.

In addition to that, I've been working on a small script that hooks directly into the loaded page in the browser and alters the tickrate live for either a set period of time or indefinitely, and reports back however often you want it to. This will also be able to implement strategies, so that gives us a way to run longterm manual tests, say overnight. Since it's attached to the browser, however, it is also limited to 60fps or 1hr/minute.

Is there a reason we are unable to calculate multiple ticks of production at a time? I don't with my simulator because I want to be able to hit the decision-making logic every tick, but what's stopping us from doing it, say, every 15 ticks?

**Comment by angarg12** [comment]
I don't think there would be any problem simulating several cycles at once.

That page hack sounds great. I was thinking about implementing some kind of cheat system to speed up manual test, so that could work.

Good then, I will close this issue for the time being since we aren't going to action on it. If necessary we can always go back and reopen.
