### ISSUE TITLE
Create a Resources dashboard

### ISSUE THREAD

**Issue by angarg12** [angarg12/incremental_table_elements#13]
As the number of total resources increases dramatically, players need to more easily manage their economy.

A resources dashboard would summarise the current status of all the resources in the game.

The dashboard would appear as a new tab.

The dashboard would feature a number of columns to display different resources.

The dashboard would include filters to limit what resources to show.

The dashboard could include a counter next to each resource estimating the generation of each resource (could be negative if the resource is being spent). This feature is subject to the technical complexity of its implementation.

**Comment by HeinousTugboat** [comment]
Here's some [example markup](https://gist.github.com/HeinousTugboat/8083972984ce49109224d37f8b491095) I threw together for my idea for this. We could have a toggle between exotics and sum resources for each element. We could gray them out if they're inaccessible, or even just not show them, and use other color coding and symbols to represent active reactions or resource starvation. If you include resource caps like I sort of alluded to in #104, this could also include a representation of how close each element is to its cap.

If you like this idea, I can start working on marking up a prototype that works inside the app. That'll take me a bit longer, though. I'm not super familiar with AngularJS, I've only really used Angular 2/4.

**Comment by angarg12** [comment]
Your proposal is not exactly what I had in mind, although it's close to another QoL improvement which is a condensed view for the periodic table.

My current vision is the following: to have a tab where the whole screen is filled only with your resources information. Potentially include several filters.

The idea is that during mid and late game players will have hundreds of resources to look at, and it will be useful (if not plain necessary!) to be able to access all info at once.

If such a panel is in place, then more and more functionality could be added on top. I image it would be very useful and relatively simple to add the change in amount next to each resource so that players can quickly identify the rate of each one. Even more advance, you could add a breakdown of the + and - of each resource. I imagine this would be very useful when you have long and complex chains of dependencies or if one of your resources is 'in red'.

If necessary I can put together a few scribbles with my thoughts.

Nevertheless the reason why I marked this feature a 'future' is because I think it could be useful, but I rather be reactive about it. It is unwise to spend time and effort in a late game feature when we can't even manage to get people pass the early game! If needed a very simple version of this feature could be included, and improvements made over time.

**Comment by HeinousTugboat** [comment]
So.. I got to where I'd unlocked all of 4 elements (H, He, Li and C..), and pretty much instantly got frustrated by the current UI. Coupled with the rapid prestige-cycling across 4 separate tabs, and the fact that you lose all Exotic particles and upgrades when you pull the dark matter prestige, you pretty much have to keep bouncing around to get anywhere. So, on that note, I've spent last night and today working on this.

![2017 09 09 - nucleogenesis - dashboard prototype](https://user-images.githubusercontent.com/15902166/30245427-2d9ebf3a-95a7-11e7-8bb8-f3b322ab399f.png)

I'd love to know what you think. It's purely an HTML/CSS prototype right now, but it's pretty responsive and will give us plenty of room to work with sorting/moving each element's card around. I figured since each element has its own upgrades and prestige cycle, it makes more sense to keep all of that self contained and separate from eV upgrades and dark matter prestiges. Down the road we can also set it up to use, say, a minimal display where it only shows you a particular generator for instance or even get rid of that whole part of the display and just see the rates/amounts at the top. I've designed this keeping tooltips in mind, and thinking about using a help screen if we need to that just briefly explains what each piece is. I don't mind implementing all of that stuff, I just want to make sure this is a good direction to go in before I start working up the rest of the tabs.

Finally, there's also plenty of working room in the sidebar, where we can put whatever you want. On top of that, this sidebar's about 20% narrower than the current one we're using. And the cards will line up however many to a row as will fit in the window. Each card's locked down to 300px wide, so the game should still at least be manageable on the tiniest of screens.

Let me know your thoughts on this, as well as any scribbles you might want to share!

**Comment by HeinousTugboat** [comment]
If you like this direction, I can start working on the other parts of the prototype, or converting the existing styles and views into this style. Otherwise, I'll go ahead and just work on adding pieces that match the current design.

**Comment by angarg12** [comment]
Wow, you put a lot of effort into it! I'm impressed by how much information you manage to convey in little space.

My only concern is how to handle ions and molecules in that mock. Would they be a separate tab on each element?

I like the concept of being able to see a lot of information at a glance and handling several elements at once. I will put together a few mocks of the ideas I had so that we can discuss them.

For reference, I work with several data dense software so I have been trying to get inspiration from them. A couple of examples are [Microsoft Azure](https://azurecomcdn.azureedge.net/mediahandler/files/videofiles/thumbnails/9240/create-a-web-app-with-aspnet-and-azure-app-service.png) and the [Kubernetes dashboard](https://d33wubrfki0l68.cloudfront.net/e6bda94ebf94cc460db5cdc42bbfdb8f95f5f7ce/fd28b/images/docs/ui-dashboard.png).

**Comment by angarg12** [comment]
Element selection concept.

I want to completely scrap the sidebar and make element selection much more concise. Here is a draft:

![img_20170910_171938](https://user-images.githubusercontent.com/5389189/30250375-72f673a6-964d-11e7-8daa-86b56af78eaa.jpg)

The idea is that there is a button that opens a modal window, and this window contains small card with all the elements that you have unlocked. You can switch element just by clicking into it.

Here is a prototype I didn't manage to finish, I hope it conveys the idea well.

https://codepen.io/anon/pen/GvRWrm

To allow multi element select it would work similarly but toggling each element.

**Comment by angarg12** [comment]
Sidebar concept.

I mostly like the current sidebar but it's a little bit crowded. Particularly when a lot of resources are unlocked, and maybe not all are relevant.

To solve this I think we could group resources by categories and nested toggles. This is taken directly from Kubernetes and other Google products like Google Analytics.

![img_20170910_173224](https://user-images.githubusercontent.com/5389189/30250424-4bd0997c-964e-11e7-814b-6e5b83980830.jpg)

Even better: at the top you could have a 'Favourites' section. Basically you can :heart: a resource, and then it is always visible at the top.

**Comment by angarg12** [comment]
General layout concept.

My idea for the global layout is to keep the sidebar with resources and the top part with the different game sections. The center would contain all the different element/tabs information.

![img_20170910_172354](https://user-images.githubusercontent.com/5389189/30250441-a2a48222-964e-11e7-99bc-63baa8e9ddae.jpg)

Here is where your concept is interesting. If possible, it would be better to display as many elements as possible on this view, possibly as cards. The question still remains, would you rather navigate each element separately or all at once?

Although I want to make the game look good, it is quite complex and I rather prioritise practicality over graphis.

**Comment by HeinousTugboat** [comment]
I'll start working on prototyping the rest of your ideas and adding them to mine. I think I'll be able to make everything work together pretty nicely. However, I do have one major concern. I realized I hadn't actually dove into reactions/redox substantially yet, so I've spent some time today with them, and the UI for that is going to be quite a nightmare. Basically, this is the problem:

![image](https://user-images.githubusercontent.com/15902166/30253087-2cf0a06c-964c-11e7-8f66-78e5e149bf6c.png)

That is every reaction Hydrogen is directly involved in, either in or out. There are worse examples. This is one place where our lives would be very greatly simplified if we limit the number of concurrent elements available. If you only have 3 elements you can react, you slice the potential reaction network down and it'll be easier to build a strong UI for.

Also, my idea here is that we can display a graph of reactions, molecules, and elements so players can navigate from molecule to molecule. We can hide any that haven't been discovered yet (or obscure them so they're visible but not identifiable). This same interface could easily double as the actual reaction interface, where you could select a specific reaction and activate it. I think there's just far, far too much information here to keep it non-visual.

**Comment by HeinousTugboat** [comment]
I've been playing with graphing formats, D3.js and Gephis this evening. Here's a lovely network overview of Hydrogen, Oxygen, Carbon and Nitrogen all combined. This chart consists of 797 nodes and 2,521 edges. This is pulled directly from `build/data/reactions.json`. Now, to be fair, the entire file has 2,248 nodes and 6,435 edges, so those 4 elements are definitely the exception not the rule, but we need to figure out how exactly we display 704 possible reactions to players in a way that's comprehensible.

[HOCN reaction network.pdf](https://github.com/angarg12/nucleogenesis/files/1291306/HOCN.reaction.network.pdf)

If you'd like to see any other networks or combinations of elements, let me know. I've got a script that takes an array of elements and returns a .dot file and a pair of .js files listing every edge and node that touches those elements and only things built from those elements.

Edit: in the attached PDF, green nodes are base elements (1H, 16O, 12C and 14N), red nodes are compounds derived from those 4 elements, and the blue nodes are various reactions. The size of the node is relative to its in-degree.

**Comment by angarg12** [comment]
What a lovely graph.

I knew displaying this information would be challenging. This is where the game goes bonkers.

However we could approach it from a different angle. When you think about it, molecules are just a crafting system in disguise. You take H2 + O and transform it into H2O.

At the moment I'm not very concerned about making a very comprehensive UI as much as to make a functional one. I envision a GUI where you have a drop down with a search box where you can choose one of your unlocked resources. Once selected a second drop down appears with a filtered list of all matches, and when you choose a second resource the corresponding reaction comes up.

First I would get such a system up and running and then improve upon it. Some basic QoL improvements would be a counter of the unlocked/total reactions for each resource so that players can easily track what they are missing.

A graph that draws all relations and you can navigate sounds amazing but would probably require a lot of design and effort implementation.

**Comment by angarg12** [comment]
BTW looking at the graph I realised something that I didn't pay much attention to.

Some of the reactions are the same reversed. For example:

NO2 + NO3 -> N2O5
N2O5 -> NO2 + NO3

Although it makes sense from the mechanic point of view, from the gameplay perspective sounds quite stupid. Why would you build up a large molecule just to break it down to the same components?

At the moment it looks like these are just adding noise to the dataset. Getting rid of them probably won't make a huge difference but would be an improvement.

**Comment by HeinousTugboat** [comment]
> When you think about it, molecules are just a crafting system in disguise. You take H2 + O and transform it into H2O.

If you look at it that way, it might be interesting to break reactions out into [reaction types](https://en.wikipedia.org/wiki/Chemical_reaction#Reaction_types) and use that as part of the unlock system. Since you're right, H2 + O => H2O is essentially a crafting recipe, but H2O => H2 + O is *also* a recipe, it's a much, much more difficult one to perform. This would require adding a whole lot of data into the system that's currently there, though. Something to consider.

From the UI perspective, my current thought is to basically display only what choices are available from current stock. That would cut down considerably on the options, but would make targeted exploration difficult. I was also thinking about whether it would be worth the effort to hand-build the trees down the road.

> Why would you build up a large molecule just to break it down to the same components?

While I agree you wouldn't walk both directions of a reaction simultaneously, it's still important to have both directions as you might produce that larger molecule from a different reaction. All the different reactions surrounding H and O for example. In any final graph, though, I do agree that I would rather use arrows like this:

![image](https://user-images.githubusercontent.com/15902166/30272651-88a11988-96c3-11e7-81f1-c7d7e85a0294.png)
