### ISSUE TITLE
Way to deal with Infinities

### ISSUE THREAD

**Issue by erplsf** [angarg12/incremental_table_elements#139]
Do you have a vision what to do when numbers reach e308 levels? At least for hydrogen it's easy to achieve in a couple of hours - for base isotopes. Maybe at least to have a way to deal with NaNs, as currently basic resource is being set to NaN after e308, which breaks prestiging for xH.

**Comment by angarg12** [comment]
Did you achieve this in the current unreleased beta?

In any event exotic matter production is up for a major overhaul that will dramatically decrease production. With the new formula, exotic matter will top out at aprox. 1e10~1e15, so regular isotopes progression will also slow down.

I haven't though of any special meaning for infinities in the end game. If reaching infinity becomes the norm I may just implement a big number library to go higher. By the way, you need more than 1e308 oganesson to survive decay for more than 1 second, so that would be the only way to accumulate this element.

**Comment by erplsf** [comment]
Yes, It's very simple process right now:
Reach 1k Exotic Matter
Buy x10 x3 upgrades
1. Reach 10x of previous achieved EM
2. Buy available EM upgrades
3. (Optionally) Apply e/p to increase EM gain on reset
4. (Optionally) Reset on 1k * x Dark Matter.
5. Repeat.

Can provide savefile, if it's needed.

**Comment by angarg12** [comment]
I think I know how it works. I'll try to push the changes to EM generation soon for testing.

**Comment by angarg12** [comment]
On the latest commit I changed the prestige formula to produce much less exotic matter.

I haven't fully tested it but now it progression should be much slower, and reaching infinite way harder.

**Comment by erplsf** [comment]
I'm using link provided in README, so I'm not sure you've deployed your changes to the site.

**Comment by angarg12** [comment]
It took me forever but version 2.7 is finally live.

**Comment by angarg12** [comment]
I did some playtesting and after the last update infinite shouldn't be an issue.

I'll leave this issue open for a couple of days and if there aren't any further comments I will close it.
