### ISSUE TITLE
Exotic tab should only show resources from the current run

### ISSUE THREAD

**Issue by primeprover** [angarg12/incremental_table_elements#161]
xH seems to always appear under Oxygen for me on the exotic page. Hopefully a quick fix. Other elements don't seem to be affected

**Comment by angarg12** [comment]
Do you have any H and O molecules?

Because of double production, you will generate exotic matter for each element in a molecule. In other words, it is intended.

We can modify the logic so that it only checks resources that you have produced on this run, which should at least hide non relevant resources.

**Comment by primeprover** [comment]
I had molecules with H and O. So prestiging Hydrogen with H20 gives you xO as well as xH?

**Comment by angarg12** [comment]
Yes, is one of the perks of molecules :smiley:

**Comment by angarg12** [comment]
I've changed the title if you don't mind, we can work on that.
