### ISSUE TITLE
Hide some late game clutter

### ISSUE THREAD

**Issue by primeprover** [angarg12/incremental_table_elements#173]
Now that I have a lot of resources unlocked(40 and counting) both the dashboard and the list of possibilities for fusion have become extremely cluttered. 
My suggestion for fusion is to have the option to remove from list resources which you don't currently have.
For the dashboard many of my resources also have 0 of them. 

The periodic table also can be a bit long. Being able to filter for unlocked/got/not got would be useful. I often end up scrolling down continually when using fusion to unlock an element.

**Comment by angarg12** [comment]
#169 Adds a legend to the elements table. We could add a 'hide' toggle next to each value so that you can hide elements based on status.

In the fusion tab we can put two improvements. First, hide resources not produced in the current run. Second, add a filter box like in the dashboard.

Let me know what you think.

**Comment by primeprover** [comment]
That sounds pretty good.

**Comment by angarg12** [comment]
Now fusion should only show isotopes generated in one of the current exotic runs, check it out.
