### ISSUE TITLE
Exotic Matter error

### ISSUE THREAD

**Issue by wjohnson8081** [angarg12/incremental_table_elements#184]
I created a molecule with sulfur and oxygen (OS) and this seems to have broken the exotic matter tab. I cannot prestige anymore, and the only thing it says is 

{{ 'EXOTIC.HIDE' | translate }}: {{ 'EXOTIC.SORT' | translate }}

**Comment by angarg12** [comment]
Interesting.

I will try to reproduce it.

Could you please pastebin your save so that I can load it up?

**Comment by wjohnson8081** [comment]
[nucleogenesis-save (1).txt](https://github.com/angarg12/nucleogenesis/files/1945479/nucleogenesis-save.1.txt)

Sorry, I'm not very tech savvy and I'm not sure what "pastebin"ing is, but I uploaded the save file here if that helps.

**Comment by angarg12** [comment]
I think I know what is the problem. Did you first do an S run, swap to O and then synthesise OS?

**Comment by wjohnson8081** [comment]
I created S through fusion of 16O and synthesised OS that way, but I didn't do an S run

**Comment by angarg12** [comment]
Even better yet.

The problem was that the game creates the exotic upgrades of elements only once you buy them.

Since you fused S that didn't create the upgrades object, and then the game was crashing with a null pointer when trying to calculate production.

I just pushed a fix, it should be live in the dev version in about 5-10 minutes.
