### ISSUE TITLE
C10H21 and C10H22  and some other molecules are not reachable

### ISSUE THREAD

**Issue by loader3229** [angarg12/incremental_table_elements#195]
C10H21 and C10H22  and some other molecules are not reachable

**Comment by angarg12** [comment]
Thanks a lot for the report.

I'll try to put together a sanity script that checks that all molecules are reachable, and cleanup the ones that aren't.

**Comment by angarg12** [comment]
So I wrote a sanity script to check that no reactions are unreachable.

I won't commit it yet since it would break the build. I compiled this list of unreachable products, which is quite long.

https://pastebin.com/q1qfGkTf

Big chunks of them are circular dependencies, so it would be fairly easy to break them up.

Before completely deleting them I would like to spend a bit of time going through them and trying to add a few more reactions instead.

**Comment by angarg12** [comment]
I've been working on this a few minutes a day, and I got the list down to ~60.
I'm trying to add 1 or 2 reactions to break each closed loop and make all reactions and molecules reachable. The easy way is to add straight combinations (e.h. A+B=AB). I'm trying to avoid those as much as possible and introduce more interesting combinations, where possible.
I couldn't find true reactions online for those elements so I am just making them up. I hope people will forgive my lack of rigor.
