### ISSUE TITLE
How the heck do I combine elements?

### ISSUE THREAD

**Issue by mechanikate** [angarg12/incremental_table_elements#198]
I've been trying to figure out how to get things like H2O (Hydrogen and Oxygen), but how do i get them both at once?

**Comment by angarg12** [comment]
Hello, thanks for your message.

Where are you right now in terms of progress?

In order to create molecules with two elements, like H and O, you need to run both of them at the same time. You can unlock an extra element slot with 25 dark matter, which allows you to run two elements at once (you can unlock more slots later on).

Specifically for H2O, you will need to combine H+H -> H2, and then H2 + O -> H2O.

Let me know if that helps.

**Comment by mechanikate** [comment]
> In order to create molecules with two elements, like H and O, you need to run both of them at the same time. You can unlock an extra element slot with 25 dark matter, which allows you to run two elements at once (you can unlock more slots later on).

Thanks for telling me this. It'd be nice if there some sort of easy way to figure that out.
