### ISSUE TITLE
Fusion running during restart causes NaNs

### ISSUE THREAD

**Issue by Sailorleo** [angarg12/incremental_table_elements#199]
If fusion is running under conditions that would produce a viable product when performing a Dark Matter reset, it keeps running after the reset and causes NaNs trying to divide by zero.

Haven't tested whether it happens with an exotic matter reset, but it probably happens there too, if one of the reactants were the element being reset.

**Comment by angarg12** [comment]
Hi,

Thanks a lot for the report, it sounds like a nasty one.

It should be easy to fix.

I'll try to set up some time to go over it.

**Comment by angarg12** [comment]
Wow that was a trip down memory lane! Thanks a lot for this. I see how terrible some of the decisions I made were (how did I cope without Typescript?).

The fix was easy, I added a unit test and made the change. However I had a lot of trouble with deps so I updated all of them to the latest version. This is quite risky, but unit test pass a quick play of the build seems ok.

It seems that my CI/CD with Travis is also gone. I have manually pushed the changes to prod. Could you please check if everything is working ok?
