### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by skywickenden** [angarg12/incremental_table_elements#4]
It's a great game. I just played through to making some water. 
1. I would have liked it if you could provide help links from the elements sidebar to the encyclopedia. Especially as the encyclopedia entries use words to describe topics, whilst the sidebar uses symbols.
2. It would also be helpful if the equations each had their own entry in the encyclopedia - also with a link next to each one.
3. I spent ages building up hydrogen then suddenly three or four equations opened up at once. It would have been nice for it to have been more staggered. I realize that you want to keep the game as true to science as possible, but the amount of hydrogen gathered before the first equation opens up seems to be arbitrary? So why not make the equations open up a little more slowly.

I look forward to the final version with all the elements in.

**Comment by angarg12** [comment]
Thanks for the feedback!
1. I really like your idea. It would reinforce the educational undertone of the game. However implementation isn't straightforward. The problem is that some resources map to many entries e.g. Tritium maps to Hydrogen, isotope and radioactivity. How to display this in the GUI? I can imagine a system where clicking in a resource opens a contextual menu "Related topics", with a list of encyclopedia entries.
2. This is harder to achieve. Only a handful of reactions have an entry in the encyclopedia because they are really important ones. The rest just describe how some compounds are transformed into others. I could like to the Chemical Reaction Database entry for each one, but this source would only be useful for really specialized people.
3. Although some unlocks have arbitrary requirements (I may change that in the future) the first reactions don't. The unlock happens after the first decay, and it can't happen any earlier, since in order to use them you need energy and sub particles, that you only get after decay. Also, since I merger the Poisson decay, it should happen much earlier, around 1 hour in. Right now I'm doing a fresh run on the game to check that everything is in order.

**Comment by skywickenden** [comment]
1. Yes. The links are not straight forward. I would add a new entry to the encyclopedia for each symbol. Which could explain it's links to the other entries. But a context menu would work as well.
2. Ahh, I missed that. Hmm; real world physics has annoyingly large amounts of nothing followed by rapid cascades of change.
