### ISSUE TITLE
Support for multi decays

### ISSUE THREAD

**Issue by angarg12** [angarg12/incremental_table_elements#66]
Some isotopes decay in more than one way, with different probability.

We should support this by producing multiple decay paths per cycle for resources, proportional to each decay.

e.g. [26Al](https://en.wikipedia.org/wiki/Aluminium) decays with beta+, electron capture and gamma radiation. Since no probabilities are shown, we assume they are equal.

Whenever a quantity of 26Al decays, we should divide the quantity in the right proportions for each decay path. On this case, we would react ~33.33% of the quantity for each decay type.

**Comment by JCBoorgo** [comment]
I'd like to try this. We'd have to play in the processDecay function, and probably play a bit in the data structure of elements.json. I would change "decay_type" to "decay_types" and make them objects, their attributes would be the decay types, which would also be objects containing the products of the decays.
```json
"decay_types": {
    "beta+": {
        "product1": 10,
        "product2": 86
    },
    "gamma": {
        "product3": 3.14,
        "product4": 42,
    }
}
```
Does this make sense? (yes, some other sections of the code would be altered, but I figure we have to anyway) (also, since halflife is shared between decay types, we can leave it there as it is in the structure)

**Comment by angarg12** [comment]
Yes, that's right. Also we should include the ration inside each decay type, just like with isotopes.

For the code, we would iterate on the decay_types object and multiply the ratio by the total amount of decays.
