### ISSUE TITLE
Exotic Matter / Dark Matter doesn't consume subatomics

### ISSUE THREAD

**Issue by boozledorf** [angarg12/incremental_table_elements#86]
Not sure if this is intentional or not, but when prestiging for Exotic Matter, using subatomic particles to boost your prestige will dramatically boost how much EM you get, but doesn't consume these particles.  Additionally, when boosting to Dark Matter, enough e- and e+ will let you go from a single Hydrogen atom to ~10^8 xH within 5 minutes, and from there, it explodes.

**Comment by angarg12** [comment]
Hello, thanks for your feedback.

The first point is definitely a bug, thanks for the report.

The second point is intentional. Meta resources are intended to boost your meta progression, although progression hasn't been balanced yet.

Does diminishing returns on the infuse boost seem like a reasonable approach?

**Comment by boozledorf** [comment]
I think that might be a reasonable approach, but scaling too harshly might prevent late-game prestige from collecting at all.

**Comment by angarg12** [comment]
I have pushed an update with bugfixes.

Also I include diminishing returns on infusion, but to make it less gruesome I boosted the infusion power.

To be honest I haven't taken the time yet to do a basic balance/pacing pass at the game. Right now it is feature complete, waiting to fill in the rest of the content.

If you want to leave general feedback on the progression/pacing for the time being it is very welcome.
